#!/usr/bin/python
#Nikolas Strepis 4-2014
#Script for matching the sequences with the database results and then with the fasta file of the database to receive the full names using xml file output from blastp
import os, sys ,fnmatch , numpy, collections

def findFiles (path, filter):
    for root, dirs, files in os.walk(path):
        for file in fnmatch.filter(files, filter):
            yield os.path.join(root, file)


file1 = open ('/Users/NikolasStrepis/Desktop/uniprot.tab')
file2 = open ("/Users/NikolasStrepis/Desktop/EC_numbers.tab", "w")

dict1={}
ec =""

for index,lines in enumerate(file1):
	#print lines

	if "(EC" in lines:
		eca = lines.strip().split("(EC")[1].split(")")[0]
		print eca
		#ecb =  lines.strip().split("(EC")[1].split(")")[0]

		dict1[lines]=eca

for key in dict1:

	file2.write(dict1[key] + "\n")

